### ISSUE TITLE
hello_windows example - Maximum Supported Texture Size - Ultra Wide Screen Support

### ISSUE THREAD

**Issue by MichealReed** [gfx-rs/wgpu-native#381]
```
thread 'main' panicked at wgpu\src\backend\wgpu_core.rs:751:18:
Error in Surface::configure: Validation Error

Caused by:
    `Surface` width and height must be within the maximum supported texture size. Requested was (3824, 1020), maximum extent for either dimension is 2048.

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When attempting to run the example with a super ultra-wide monitor, I receive the error. I found this issue with a list of the texture size limits per platform

https://github.com/gpuweb/gpuweb/issues/1327

and do not see any reason this error should occur unless a 3D texture is being used for the surface.

Could the limits be mapped incorrectly? Is this an issue with the bindings or wgpu?

**Comment by radgeRayden** [comment]
We just pushed code that touches this, could you retest?

**Comment by MichealReed** [comment]
With a clean build

```
Caused by:
    `Surface` width and height must be within the maximum supported texture size. Requested was (3824, 984), maximum extent for either dimension is 2048.
```

Seems the Y value did change but the error persists.

**Comment by rajveermalviya** [comment]
Hey, @MichealReed seems like this issue was meant for [`wgpu`](https://github.com/gfx-rs/wgpu) and not `wgpu-native`, as the [`hello_windows`](https://github.com/gfx-rs/wgpu/tree/trunk/examples/src/hello_windows) example is part of `wgpu` not `wgpu-native`. Can you please confirm this?

Also the cause for that is because [downlevel_limits](https://github.com/gfx-rs/wgpu/blob/9df68197a4d533dc919a38bfafedf85912668e98/examples/src/hello_windows/mod.rs#L77) are used as required device limits in that example, and `max_texture_dimension_2d` in downlevel is 2048. A simple fix would be to [override](https://github.com/gfx-rs/wgpu/blob/9df68197a4d533dc919a38bfafedf85912668e98/examples/src/hello_triangle/mod.rs#L33-L34) them with adapter texture resolution limits.

**Comment by MichealReed** [comment]
> Hey, @MichealReed seems like this issue was meant for [`wgpu`](https://github.com/gfx-rs/wgpu) and not `wgpu-native`, as the [`hello_windows`](https://github.com/gfx-rs/wgpu/tree/trunk/examples/src/hello_windows) example is part of `wgpu` not `wgpu-native`. Can you please confirm this?
> 
> Also the cause for that is because [downlevel_limits](https://github.com/gfx-rs/wgpu/blob/9df68197a4d533dc919a38bfafedf85912668e98/examples/src/hello_windows/mod.rs#L77) are used as required device limits in that example, and `max_texture_dimension_2d` in downlevel is 2048. A simple fix would be to [override](https://github.com/gfx-rs/wgpu/blob/9df68197a4d533dc919a38bfafedf85912668e98/examples/src/hello_triangle/mod.rs#L33-L34) them with adapter texture resolution limits.

That makes sense and the workaround is appreciated. Will open an issue with https://github.com/gfx-rs/wgpu given that 2048 is quite low and likely should be raised to 4k or 8k.
